# Generated by Django 2.2.5 on 2021-03-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('symbol', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
