# Generated by Django 2.2.5 on 2021-02-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20210219_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='contributors',
            field=models.TextField(null=True),
        ),
    ]
