# Generated by Django 2.2.5 on 2021-03-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_auto_20210308_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunarcrushtimeentries',
            name='tweet_replies',
            field=models.IntegerField(null=True),
        ),
    ]
