# Generated by Django 2.2.5 on 2021-03-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_lunarcrushtimeentries_tweet_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunarcrushtimeentries',
            name='market_cap',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lunarcrushtimeentries',
            name='unique_url_shares',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lunarcrushtimeentries',
            name='url_shares',
            field=models.IntegerField(null=True),
        ),
    ]
