# Generated by Django 2.2.5 on 2021-03-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_lunarcrushinfluencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunarcrushinfluencer',
            name='asset',
            field=models.TextField(null=True),
        ),
    ]
