# Generated by Django 2.2.5 on 2021-03-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_lunarcrushinfluencer_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('symbol', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='lunarcrushinfluencer',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.Asset'),
        ),
    ]
