# Generated by Django 2.2.5 on 2021-03-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0013_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunarcrushtimeentries',
            name='close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lunarcrushtimeentries',
            name='high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lunarcrushtimeentries',
            name='low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lunarcrushtimeentries',
            name='open',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lunarcrushtimeentries',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lunarcrushtimeentries',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
