# Generated by Django 2.2.5 on 2021-03-13 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_auto_20210310_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessariAPI',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(null=True)),
                ('open', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.Asset')),
            ],
        ),
    ]
