# Generated by Django 2.2.5 on 2021-03-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0016_auto_20210313_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='messariapi',
            name='bitwise_volume',
            field=models.FloatField(null=True),
        ),
    ]
