# Generated by Django 2.2.5 on 2021-03-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0017_messariapi_bitwise_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='messariapi',
            name='real_volume',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='messariapi',
            name='reddit_subscribers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messariapi',
            name='reddit_users',
            field=models.IntegerField(null=True),
        ),
    ]
