# Generated by Django 2.2.5 on 2021-03-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0018_auto_20210314_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='messariapi',
            name='active_addresses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messariapi',
            name='average_transfer_value_usd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='messariapi',
            name='blocks_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messariapi',
            name='flow_in_usd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='messariapi',
            name='flow_out_usd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='messariapi',
            name='mean_difficulty',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='messariapi',
            name='sharpe_1yr',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='messariapi',
            name='sharpe_30d',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='messariapi',
            name='sharpe_3yr',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='messariapi',
            name='sharpe_90d',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='messariapi',
            name='transactions_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messariapi',
            name='transfers_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messariapi',
            name='transfers_volume',
            field=models.FloatField(null=True),
        ),
    ]
