# Generated by Django 2.2.5 on 2021-03-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0019_auto_20210314_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='messariapi',
            name='interval',
            field=models.FloatField(default=3600, null=True),
        ),
    ]
