# Generated by Django 2.2.5 on 2021-03-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0021_auto_20210315_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='token_is_treasury_centralized',
            new_name='token_is_treasury_decentralized',
        ),
    ]
