# Generated by Django 2.2.5 on 2021-03-19 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0023_asset_market_cap_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_asset', to='model.Asset')),
                ('quote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_asset', to='model.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('open_time', models.DateTimeField(null=True)),
                ('close_time', models.DateTimeField(null=True)),
                ('interval', models.TextField()),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('quote_volume', models.FloatField(null=True)),
                ('trades', models.IntegerField(null=True)),
                ('taker_buy_asset_volume', models.FloatField(null=True)),
                ('taker_buy_quote_volume', models.FloatField(null=True)),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.Symbol')),
            ],
        ),
    ]
