# Generated by Django 2.2.5 on 2021-03-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0025_exchangedata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
