# Generated by Django 2.2.5 on 2021-03-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0026_exchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangedata',
            old_name='name',
            new_name='exchange',
        ),
    ]
