# Generated by Django 2.2.5 on 2021-03-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0027_auto_20210319_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangedata',
            name='exchange_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.Exchange'),
        ),
    ]
