# Generated by Django 2.2.5 on 2021-03-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0028_exchangedata_exchange_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangedata',
            name='exchange',
        ),
    ]
