# Generated by Django 2.2.5 on 2021-03-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0029_remove_exchangedata_exchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangedata',
            old_name='exchange_info',
            new_name='exchange',
        ),
    ]
