# Generated by Django 2.2.5 on 2021-03-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0030_auto_20210322_1118'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangedata',
            unique_together={('open_time', 'exchange', 'interval', 'symbol')},
        ),
    ]
