# Generated by Django 3.1.7 on 2021-04-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0031_auto_20210324_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedata',
            name='open_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
