# Generated by Django 3.1.7 on 2021-04-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0032_auto_20210407_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuredData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField(db_index=True, null=True)),
                ('close_time', models.DateTimeField(null=True)),
                ('interval', models.TextField()),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('quote_volume', models.FloatField(null=True)),
                ('trades', models.IntegerField(null=True)),
                ('taker_buy_asset_volume', models.FloatField(null=True)),
                ('taker_buy_quote_volume', models.FloatField(null=True)),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.exchange')),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.symbol')),
            ],
            options={
                'unique_together': {('open_time', 'exchange', 'interval', 'symbol')},
            },
        ),
    ]
