# Generated by Django 3.1.7 on 2021-04-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0035_auto_20210409_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lunarcrushtimeentries',
            old_name='time',
            new_name='open_time',
        ),
        migrations.AlterField(
            model_name='lunarcrushtimeentries',
            name='asset',
            field=models.TextField(null=True),
        ),
    ]
