# Generated by Django 3.1.7 on 2021-04-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0036_auto_20210409_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunarcrushtimeentries',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.asset'),
        ),
    ]
