# Generated by Django 3.1.7 on 2021-04-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0037_auto_20210409_0703'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lunarcrushtimeentries',
            unique_together={('open_time', 'asset')},
        ),
    ]
