# Generated by Django 3.1.7 on 2021-04-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0038_auto_20210409_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunarcrushtimeentries',
            name='market_cap',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lunarcrushtimeentries',
            name='market_cap_global',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lunarcrushtimeentries',
            name='social_score',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lunarcrushtimeentries',
            name='volume',
            field=models.BigIntegerField(null=True),
        ),
    ]
