# Generated by Django 3.1.7 on 2021-04-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0039_auto_20210409_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messariapi',
            old_name='time',
            new_name='open_time',
        ),
    ]
