# Generated by Django 3.1.7 on 2021-04-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0041_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
