# Generated by Django 3.1.7 on 2021-04-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0042_auto_20210410_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_id',
            field=models.TextField(null=True),
        ),
    ]
