# Generated by Django 3.2 on 2021-04-15 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0044_auto_20210415_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='exchange',
            field=models.ForeignKey(default='binance', on_delete=django.db.models.deletion.CASCADE, to='model.exchange'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='jobs',
            unique_together={('job_id', 'exchange', 'app')},
        ),
    ]
