# Generated by Django 3.1.7 on 2021-12-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0047_auto_20211206_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
