# Generated by Django 3.1.7 on 2021-12-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0048_pipeline_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='params',
            field=models.TextField(blank=True, null=True),
        ),
    ]
