# Generated by Django 3.1.7 on 2021-12-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0049_pipeline_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together={('symbol', 'interval', 'strategy', 'params', 'exchange')},
        ),
    ]
