# Generated by Django 3.1.7 on 2021-12-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0050_auto_20211206_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='paper_trading',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
