# Generated by Django 3.1.7 on 2021-12-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0051_auto_20211208_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='params',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
