# Generated by Django 3.1.7 on 2021-12-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0052_auto202111208_0531'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together={('symbol', 'interval', 'strategy', 'params', 'exchange', 'paper_trading')},
        ),
    ]
