# Generated by Django 3.2 on 2021-12-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0053_auto_20211208_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='strategy',
            field=models.TextField(),
        ),
    ]
