# Generated by Django 3.2 on 2021-12-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0055_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.pipeline'),
        ),
        migrations.AddField(
            model_name='position',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.pipeline'),
        ),
        migrations.AlterField(
            model_name='position',
            name='open_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
