# Generated by Django 3.2 on 2022-01-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0056_auto_20211211_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
