# Generated by Django 3.2 on 2022-01-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0057_position_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.IntegerField(),
        ),
    ]
