# Generated by Django 3.2 on 2022-01-16 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0058_alter_position_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('type', models.TextField()),
                ('side', models.TextField()),
                ('mock', models.BooleanField(default=False, null=True)),
                ('exchange', models.ForeignKey(default='binance', on_delete=django.db.models.deletion.SET_DEFAULT, to='model.exchange')),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.pipeline')),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.symbol')),
            ],
        ),
    ]
