# Generated by Django 3.2 on 2022-01-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0059_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
