# Generated by Django 3.2 on 2022-01-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0060_alter_trade_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='price',
            new_name='open_price',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='time',
            new_name='open_time',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='type',
        ),
        migrations.AddField(
            model_name='trade',
            name='close_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='profit_loss',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
