# Generated by Django 3.2 on 2022-01-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0061_auto_20220116_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='side',
            field=models.IntegerField(),
        ),
    ]
