# Generated by Django 3.2 on 2022-01-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0063_pipeline_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='allocation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
