# Generated by Django 3.2 on 2022-02-01 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0064_auto_20220128_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='color',
            field=models.TextField(default='rgba(100, 100, 100, 0.8)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.pipeline'),
        ),
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together={('name', 'symbol', 'interval', 'strategy', 'params', 'exchange', 'paper_trading')},
        ),
    ]
