# Generated by Django 3.1.7 on 2022-10-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0065_auto_20220201_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
