# Generated by Django 3.1.7 on 2022-11-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0066_auto_20221008_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='leverage',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
