# Generated by Django 3.1.7 on 2022-11-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0067_pipeline_leverage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together={('name', 'symbol', 'interval', 'strategy', 'params', 'exchange', 'paper_trading', 'leverage')},
        ),
    ]
