# Generated by Django 3.1.7 on 2022-11-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0069_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=255, unique=True, verbose_name='username'),
        ),
    ]
