# Generated by Django 3.2 on 2023-01-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0071_auto_20221130_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='buying_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
