# Generated by Django 3.2 on 2023-01-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0073_alter_position_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
