# Generated by Django 3.2.16 on 2023-02-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0075_auto_20230128_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='price_precision',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symbol',
            name='quantity_precision',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
