# Generated by Django 3.2 on 2023-02-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0076_auto_20230204_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='leverage',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
