# Generated by Django 3.2.17 on 2023-03-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0077_trade_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='balance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='units',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
