# Generated by Django 3.2.17 on 2023-04-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0078_auto_20230325_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='last_entry',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
