# Generated by Django 3.2.17 on 2023-04-22 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0079_pipeline_last_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('value', models.FloatField()),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.pipeline')),
            ],
        ),
    ]
