# Generated by Django 3.2.17 on 2023-04-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0080_portfoliotimeseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotimeseries',
            name='type',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
