# Generated by Django 3.2.17 on 2023-05-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0081_portfoliotimeseries_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline',
            old_name='allocation',
            new_name='equity',
        ),
    ]
