# Generated by Django 3.2.23 on 2023-12-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0082_rename_allocation_pipeline_equity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('params', models.TextField(blank=True, default='{}')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together={('name', 'symbol', 'interval', 'exchange', 'paper_trading', 'leverage')},
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='params',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='strategy',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='strategy',
            field=models.ManyToManyField(to='model.Strategy'),
        ),
    ]
