# Generated by Django 3.2.23 on 2023-12-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0084_run_strategy_migration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together={('name', 'symbol', 'interval', 'exchange', 'paper_trading', 'leverage')},
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='params',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='strategy',
        ),
        migrations.RenameField(
            model_name='pipeline',
            old_name='strategies',
            new_name='strategy',
        ),
    ]
