# Generated by Django 3.2.23 on 2023-12-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0085_auto_20231209_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='params',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
