# Generated by Django 3.2.23 on 2024-01-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0086_alter_strategy_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='strategy_combination',
            field=models.TextField(choices=[('Unanimous', 'Unanimous'), ('Majority', 'Majority')], default='Majority'),
        ),
    ]
