# Generated by Django 3.2.23 on 2024-01-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0088_alter_pipeline_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline',
            old_name='equity',
            new_name='initial_equity',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='current_equity',
            field=models.FloatField(null=True),
        ),
    ]
