# Generated by Django 3.2.23 on 2024-01-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0090_run_current_equity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='profit_loss',
            new_name='pnl_pct',
        ),
        migrations.AddField(
            model_name='trade',
            name='pnl',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
