# Generated by Django 3.2.24 on 2024-02-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0094_auto_20240227_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='restarted',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
