# Generated by Django 3.2.24 on 2026-06-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0095_pipeline_restarted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exchangedata',
            index=models.Index(fields=['symbol', 'interval', 'open_time'], name='model_excha_symbol__a78153_idx'),
        ),
        migrations.AddIndex(
            model_name='structureddata',
            index=models.Index(fields=['symbol', 'interval', 'open_time'], name='model_struc_symbol__0773c1_idx'),
        ),
    ]
