# Generated by Django 4.2.30 on 2026-06-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0098_position_unique_pipeline"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                ("key", models.TextField(primary_key=True, serialize=False)),
                ("value", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
