from strategies.backtesting.iterative.sma import SMAIterBacktester
from strategies.backtesting.iterative.momentum import MomentumIterBacktester
# from strategies.backtesting.iterative.predictive import MLVectBacktester
from strategies.backtesting.iterative.mean_reversion import MeanRevIterBacktester
