from model.strategies.moving_average.ma import MovingAverage
from model.strategies.moving_average.ma_crossover import MovingAverageCrossover
from model.strategies.moving_average.macd import MovingAverageConvergenceDivergence
