from quant_model.strategies.moving_average.ma import MovingAverage
from quant_model.strategies.moving_average.ma_crossover import MovingAverageCrossover
from quant_model.strategies.moving_average.macd import MovingAverageConvergenceDivergence
