# Generated by Django 2.2.5 on 2021-02-19 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('followers_count', models.IntegerField()),
                ('friends_count', models.IntegerField()),
                ('listed_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('favourites_count', models.IntegerField()),
                ('statuses_count', models.IntegerField()),
                ('media_count', models.IntegerField()),
                ('blocked_by', models.BooleanField()),
                ('blocking', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('full_text', models.TextField()),
                ('number_hashtags', models.IntegerField()),
                ('number_symbols', models.IntegerField()),
                ('user_mentions', models.IntegerField()),
                ('number_urls', models.IntegerField()),
                ('number_media', models.IntegerField()),
                ('in_reply_to_status', models.BooleanField()),
                ('has_quoted_status', models.BooleanField()),
                ('contributors', models.TextField()),
                ('retweet_count', models.IntegerField()),
                ('favourite_count', models.IntegerField()),
                ('reply_count', models.IntegerField()),
                ('quote_count', models.IntegerField()),
                ('possibly_sensitive', models.BooleanField(default=False)),
                ('hashtags', models.ManyToManyField(to='model.Hashtag')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.TwitterUser')),
            ],
        ),
    ]
