# Generated by Django 2.2.5 on 2021-02-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
