# Generated by Django 2.2.5 on 2021-02-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20210219_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
