# Generated by Django 2.2.5 on 2021-03-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_lunarcrushtimeentries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunarcrushtimeentries',
            name='asset',
            field=models.TextField(unique_for_date='time'),
        ),
    ]
