# Generated by Django 2.2.5 on 2021-03-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_auto_20210308_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunarCrushInfluencer',
            fields=[
                ('twitter_screen_name', models.TextField(primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
                ('volume', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('engagement', models.IntegerField()),
                ('volume_rank', models.IntegerField()),
                ('followers_rank', models.IntegerField()),
                ('engagement_rank', models.IntegerField()),
            ],
        ),
    ]
