google_api_headers = {
    'authority': 'www.googleapis.com',
    'method': 'POST',
    'path': '/identitytoolkit/v3/relyingparty/verifyPassword?key=AIzaSyBAMtbrsRL6tnE_INeT7l04U2CjzeRhb3w',
    'scheme': 'https',
    'accept': '*/*',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-US,en;q=0.9,pt;q=0.8,es;q=0.7',
    'cache-control': 'no-cache',
    'content-length': '88',
    'content-type': 'application/json',
    'origin': 'https://lunarcrush.com',
    'pragma': 'no-cache',
    'referer': 'https://lunarcrush.com/',
    'sec-ch-ua': '"Chromium";v="88", "Google Chrome";v="88", ";Not A Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'cross-site',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36',
    'x-client-version': 'Chrome/JsCore/8.0.1/FirebaseCore-web',
}


lunarcrush_headers = {
    'authority': 'api.lunarcrush.com',
    'method': 'GET',
    'path': '/v2/assets?data=assets&symbol=btc&change=1d%2C1w%2C1m%2C3m%2C6m%2C1y&data_points=365&interval=day&key=b85hxrqox4oookp43nsk9',
    'scheme': 'https',
    'accept': 'application/json, text/plain, */*',
    'accept-encoding': 'gzip, deflate, br',
    'origin': 'https://lunarcrush.com',
    'referer': 'https://lunarcrush.com/',
    'sec-ch-ua': '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
    'sec-ch-ua-mobile': '?0',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-site',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36'
}


def get_headers(token):
    return {
    'authority': 'us-central1-coin-insights.cloudfunctions.net',
    'method': 'POST',
    'path': '/apiRequest',
    'scheme': 'https',
    'authorization': f'Bearer {token}',
    'accept': '*/*',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-US,en;q=0.9,pt;q=0.8,es;q=0.7',
    'cache-control': 'no-cache',
    'content-length': '105',
    'content-type': 'application/json',
    'origin': 'https://lunarcrush.com',
    'pragma': 'no-cache',
    'referer': 'https://lunarcrush.com/',
    'sec-ch-ua': '"Chromium";v="88", "Google Chrome";v="88", ";Not A Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'cross-site',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36',
}