# Your workflow name.
name: Build and Deploy crypto-bot-quant-model to heroku.

# Run workflow on every push to master branch.
on:
  push:
    branches: [master]
    paths:
      - 'quant_model/**'
      - 'shared/**'
      - '.github/workflows/build-deploy-quant-model.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to heroku container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          heroku container:login
      - name: Build and push
        env:
          DIRECTORY: quant_model/
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_MODEL_APP_NAME }}
        run: |
          cd $DIRECTORY
          heroku container:push --recursive --app $HEROKU_APP_NAME --context-path=../ --arg APP_NAME=$HEROKU_APP_NAME
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_MODEL_APP_NAME }}
          HEROKU_WEB_PROCESS: web
          HEROKU_WORKER_PROCESS: worker
        run: heroku container:release $HEROKU_WEB_PROCESS $HEROKU_WORKER_PROCESS --app $HEROKU_APP_NAME