# Your workflow name.
name: Build and Deploy crypto-bot-data to heroku.

# Run workflow on every push to master branch.
on:
  push:
    branches: [master]
    paths:
      - 'database/model/migrations/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Heroku Login
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_DATA_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          justlogin: true
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_DATA_APP_NAME }}
      - run: heroku run python database/manage.py migrate --app $HEROKU_APP_NAME

